### ISSUE TITLE
求助如何对kibana做认证

### ISSUE THREAD

**Issue by zwp201301** [shanghai-edu/nginx-ldap-auth#2]
我看示例nginx.conf已经有配置Upstream，但是在后面并没有用到。
我按照readme，启动成功，访问登录界面，输入ldap的用户名和密码，也是正确的。

跳转到的是本地示例服务localhost:8080，我的理解是应该跳转到kibana网址。

还是说，我刚开始输入的就应该是Kibana的域名，发现它是需要认证的，就跳转到ldap的登录页面。

多少对于使用来说，有点换乱了，望赐教

**Comment by freedomkk-qfeng** [comment]
这里的机制本是上通过的 nginx 的 auth-request 模块
官方的 demo 见 https://github.com/nginxinc/nginx-ldap-auth
你可能需要调整你的 nginx 配置。
这个仓库是一个 golang 的实现方式
