### ISSUE TITLE
Bug: assignment mismatch: 2 variables but TimeCheck returns 1 value

### ISSUE THREAD

**Issue by TieWay59** [shanghai-edu/nginx-ldap-auth#5]
> assignment mismatch: 2 variables but TimeCheck returns 1 value

https://github.com/shanghai-edu/nginx-ldap-auth/blob/b42befd9c035a3ebb7d201dba9419387c7add958/utils/time_test.go#L7-L9

如上代码中 `TimeCheck` 函数只有一个返回值，所以这部分代码报错。

**Comment by freedomkk-qfeng** [comment]
测试用例未更新，可以改为测试 timeCheck 函数，他有2个返回值。
但对应需要更改为遍历 timeRanges 并逐个放入 timeCheck 测试，如果有 err 则 t.Error(err) 将其抛出

**Comment by freedomkk-qfeng** [comment]
fixed
